sonar.projectKey=dotnetCleanArchitechtureScan
sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar
sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend
sonar.pullrequest.cache.basepath=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend
sonar.sources=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_0.Backing_Service/db/MssqlDB/docker-compose.yaml",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_0.Backing_Service/db/MongoDB/docker-compose.yaml"

7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.projectKey=dotnetCleanArchitechtureScan:7DF6B343-B358-4230-A897-8861EDE0B14E
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.projectName=_1.Domain
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.sourceEncoding=utf-8
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.tests=
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.sources=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/Common/BaseEntity.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/Entities/Blogs.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/Entities/Products.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/Interfaces/IBlogsRepository.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/Interfaces/IProductsRepository.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/obj/_1.Domain.csproj.nuget.dgspec.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/obj/project.assets.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/obj/Debug/net8.0/_1.Domain.sourcelink.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_1.Domain/bin/Debug/net8.0/_1.Domain.deps.json"

7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.cs.analyzer.projectOutPaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/0"
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.cs.roslyn.reportFilePaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/0/Issues.json"
7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.cs.scanner.telemetry=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/0/Telemetry.json"

7DF6B343-B358-4230-A897-8861EDE0B14E.sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar/mod0
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.projectKey=dotnetCleanArchitechtureScan:0F43A315-098C-45E5-9E10-C0BFD9285D4C
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.projectName=_2.Application
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.sourceEncoding=utf-8
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.tests=
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.sources=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/obj/_2.Application.csproj.nuget.dgspec.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/obj/project.assets.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/obj/Debug/net8.0/_2.Application.sourcelink.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/bin/Debug/net8.0/_2.Application.deps.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Common/Constants/ErrorCodes.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Common/Exceptions/NotFoundException.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Common/Models/Result.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/DTOs/BlogsDto.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/DTOs/ProductsDto.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Interfaces/IBlogsService.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Interfaces/IProductsService.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Services/BlogsService.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Services/ProductsService.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_2.Application/Settings/DbSettings.cs"

0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.cs.analyzer.projectOutPaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/1"
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.cs.roslyn.reportFilePaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/1/Issues.json"
0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.cs.scanner.telemetry=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/1/Telemetry.json"

0F43A315-098C-45E5-9E10-C0BFD9285D4C.sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar/mod1
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.projectKey=dotnetCleanArchitechtureScan:1C6F1557-80DD-4578-B29F-DB3F84EFFC44
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.projectName=_4.WebApi
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.sourceEncoding=utf-8
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.tests=
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.sources=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/appsettings.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/appsettings.Development.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/_4.WebApi.csproj.nuget.dgspec.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/project.assets.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/Properties/launchSettings.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/staticwebassets.build.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/_4.WebApi.sourcelink.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/bin/Debug/net8.0/_4.WebApi.deps.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/bin/Debug/net8.0/appsettings.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/bin/Debug/net8.0/_4.WebApi.runtimeconfig.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/bin/Debug/net8.0/appsettings.Development.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/Controllers/BlogsController.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/Controllers/ProductsController.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/Program.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/_4.WebApi.GlobalUsings.g.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/_4.WebApi.AssemblyInfo.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/obj/Debug/net8.0/_4.WebApi.MvcApplicationPartsAssemblyInfo.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_4.WebApi/_4.WebApi.http"

1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.cs.analyzer.projectOutPaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/4"
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.cs.roslyn.reportFilePaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/4/Issues.json"
1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.cs.scanner.telemetry=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/4/Telemetry.json"

1C6F1557-80DD-4578-B29F-DB3F84EFFC44.sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar/mod2
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.projectKey=dotnetCleanArchitechtureScan:51414FA2-2323-4F7F-B8D5-6A03EED75AC5
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.projectName=_5.Tests
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.sourceEncoding=utf-8
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.sources=
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.tests=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/obj/_5.Tests.csproj.nuget.dgspec.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/obj/project.assets.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/obj/Debug/net8.0/_5.Tests.sourcelink.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/bin/Debug/net8.0/_5.Tests.runtimeconfig.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/bin/Debug/net8.0/_5.Tests.deps.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/Application/ProductServiceTests.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/Domain/ProductTests.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/Infrastructure/ProductRepositoryTests.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_5.Tests/TestResults/2ecf3e85-1516-473b-96e4-9355dd5061f6/coverage.cobertura.xml"

51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.cs.analyzer.projectOutPaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/3"
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.cs.roslyn.reportFilePaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/3/Issues.json"
51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.cs.scanner.telemetry=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/3/Telemetry.json"

51414FA2-2323-4F7F-B8D5-6A03EED75AC5.sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar/mod3
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.projectKey=dotnetCleanArchitechtureScan:8B48265C-9603-41C5-B8AB-23B1355CEA2C
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.projectName=_3.Infrastructure
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.projectBaseDir=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.sourceEncoding=utf-8
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.tests=
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.sources=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/obj/_3.Infrastructure.csproj.nuget.dgspec.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/obj/project.assets.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/obj/Debug/net8.0/_3.Infrastructure.sourcelink.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/bin/Debug/net8.0/_3.Infrastructure.deps.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/bin/Debug/net8.0/_3.Infrastructure.runtimeconfig.json",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Migrations/20250621083111_CreateTableProducts.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Migrations/20250621083111_CreateTableProducts.Designer.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Migrations/MssqlDbContextModelSnapshot.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MongoDB/DBContext/MongoDbContext.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MongoDB/Repositories/BlogsRepository.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MongoDB/Repositories/ProductsRepository.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MSSQL/Configurations/ProductsConfiguration.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MSSQL/DBContext/MssqlDbContext.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MSSQL/Repositories/BlogsRepository.cs",\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/_3.Infrastructure/Persistence/MSSQL/Repositories/ProductsRepository.cs"

8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.cs.analyzer.projectOutPaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/2"
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.cs.roslyn.reportFilePaths=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/2/Issues.json"
8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.cs.scanner.telemetry=\
"/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/2/Telemetry.json"

8B48265C-9603-41C5-B8AB-23B1355CEA2C.sonar.working.directory=/Users/jeerawat/Documents/project/dotnetCleanArchitecture/backend/.sonarqube/out/.sonar/mod4
sonar.host.url=http://localhost:9001
sonar.visualstudio.enable=false

sonar.modules=7DF6B343-B358-4230-A897-8861EDE0B14E,0F43A315-098C-45E5-9E10-C0BFD9285D4C,1C6F1557-80DD-4578-B29F-DB3F84EFFC44,51414FA2-2323-4F7F-B8D5-6A03EED75AC5,8B48265C-9603-41C5-B8AB-23B1355CEA2C

